module rv32i_cpu(
    input clk,
    input reset,
    output [31:0] probe_pc,
    output [31:0] probe_alu
);

    // -------------------------------------------------------------------------
    // 1. Internal Wires (The "Traces" on the Motherboard)
    // -------------------------------------------------------------------------
    // PC Wires
    wire [31:0] pc_out, pc_next, pc_plus_4, pc_target;
    wire        PCSrc;
    
    // Instruction & Immediate Wires
    wire [31:0] instruction;
    wire [31:0] imm;
    
    // Control Signals
    wire       Branch, MemRead, MemToReg, MemWrite, ALUSrc, RegWrite;
    wire [1:0] ALUOp;
    reg  [3:0] alu_ctrl; // Generated by inline ALU Decoder
    
    // Register File Wires
    wire [31:0] read_data1, read_data2, write_data;
    
    // ALU Wires
    wire [31:0] alu_in2, alu_result;
    wire        zero;
    
    // Data Memory Wires
    wire [31:0] mem_read_data;

    // -------------------------------------------------------------------------
    // 2. Program Counter & Instruction Fetch
    // -------------------------------------------------------------------------
    // PC Register (Assume standard D-Flip-Flop behavior for your PC module)
    pc u_pc (
        .clk(clk),
        .reset(reset),
        .pc_in(pc_next),
        .pc_out(pc_out)
    );

    // PC Adders
    assign pc_plus_4 = pc_out + 32'd4;
    assign pc_target = pc_out + imm;
    
    // Branch Logic (PCSrc is high only if it's a branch instruction AND the ALU outputs zero)
    assign PCSrc   = Branch & zero;
    assign pc_next = (PCSrc) ? pc_target : pc_plus_4;

    imem u_imem (
        .a(pc_out),
        .rd(instruction)
    );

    // -------------------------------------------------------------------------
    // 3. Instruction Decode & Control
    // -------------------------------------------------------------------------
    control u_control (
        .opcode(instruction[6:0]),
        .Branch(Branch),
        .MemRead(MemRead),
        .MemToReg(MemToReg),
        .ALUOp(ALUOp),
        .MemWrite(MemWrite),
        .ALUSrc(ALUSrc),
        .RegWrite(RegWrite)
    );

    regfile u_regfile (
        .clk(clk),
        .RegWrite(RegWrite),
        .rs1(instruction[19:15]),
        .rs2(instruction[24:20]),
        .rd(instruction[11:7]),
        .WriteData(write_data),      // Corrected
        .ReadData1(read_data1),      // Corrected
        .ReadData2(read_data2)       // Corrected
    );
    immgen u_immgen (
        .inst(instruction),
        .imm(imm)
    );

    // -------------------------------------------------------------------------
    // 4. Execution (ALU)
    // -------------------------------------------------------------------------
    // ALU Source Multiplexer
    assign alu_in2 = (ALUSrc) ? imm : read_data2;

    // Inline ALU Decoder (Combines ALUOp from Control Unit with funct3/funct7)
    always @(*) begin
        case (ALUOp)
            2'b00: alu_ctrl = 4'b0010; // Load/Store -> ADD
            2'b01: alu_ctrl = 4'b0110; // Branch -> SUB
            2'b10: begin               // R-type / I-type
                if (instruction[14:12] == 3'b000) begin
                    if (instruction[30] == 1'b1 && instruction[6:0] == 7'b0110011) 
                        alu_ctrl = 4'b0110; // SUB (R-type only)
                    else 
                        alu_ctrl = 4'b0010; // ADD / ADDI
                end
                else if (instruction[14:12] == 3'b111) alu_ctrl = 4'b0000; // AND
                else if (instruction[14:12] == 3'b110) alu_ctrl = 4'b0001; // OR
                else alu_ctrl = 4'b0010; // Default to ADD
            end
            default: alu_ctrl = 4'b0010;
        endcase
    end

    // ALU (Ensure your ALU module ports match these names)
    alu u_alu (
        .A(read_data1),              // Corrected
        .B(alu_in2),                 // Corrected
        .ALUControl(alu_ctrl),       // Corrected
        .Result(alu_result),         // Corrected
        .zero(zero)
    );

    // -------------------------------------------------------------------------
    // 5. Memory & Writeback
    // -------------------------------------------------------------------------
    dmem u_dmem (
        .clk(clk),
        .MemWrite(MemWrite),
        .MemRead(MemRead),
        .addr(alu_result),
        .write_data(read_data2),
        .read_data(mem_read_data)
    );

    // Writeback Multiplexer
    assign write_data = (MemToReg) ? mem_read_data : alu_result;
assign probe_pc = pc_out;
assign probe_alu = alu_result;
endmodule